apiVersion: v1
kind: Namespace
metadata:
  name: titiler
---
apiVersion: v1
kind: Service
metadata:
  name: titiler-stacapi
  namespace: titiler
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: titiler-stacapi
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: titiler-stacapi
  namespace: titiler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titiler-stacapi
  template:
    metadata:
      labels:
        app: titiler-stacapi
    spec:
      containers:
      - env:
        - name: TITILER_STACAPI_STAC_API_URL
          value: https://api.stac
        image: shahidraza0098/titiler-stacapi:latest
        imagePullPolicy: Always
        name: titiler-stacapi
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.org/location-snippets: |
      internal;
    nginx.org/mergeable-ingress-type: minion
  name: titiler-stacapi
  namespace: titiler
spec:
  ingressClassName: nginx
  rules:
  - host: titiler.test.com
    http:
      paths:
      - backend:
          service:
            name: titiler-stacapi
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.org/mergeable-ingress-type: master
  name: titiler-stacapi-master
  namespace: titiler
spec:
  ingressClassName: nginx
  rules:
  - host: titiler.test.com
    http:
      paths:
      - backend:
          service:
            name: titiler-stacapi
            port:
              number: 80
        path: /
        pathType: Prefix
