apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: titiler-stacapi
  namespace: titiler
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: titiler.test.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: titiler-stacapi
                port:
                  number: 80
