apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: titiler

resources:
  - namespace.yaml
  - deployment.yaml
  # - service.yaml
  - ingress.yaml

commonLabels:
  app: titiler-stacapi
